# Generated by Django 2.0 on 2017-12-20 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=40, verbose_name='groupname')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.CharField(default='', max_length=200, verbose_name='description')),
                ('location', models.CharField(max_length=100, null=True, verbose_name='location')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='picture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSpan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='start_time')),
                ('duration', models.DurationField(null=True, verbose_name='duration')),
                ('activity', models.CharField(choices=[('Traffic', 'Traffic'), ('Meal', 'Meal'), ('Sight seeing', 'Sight seeing')], max_length=30, verbose_name='activity')),
                ('note', models.CharField(max_length=200, null=True, verbose_name='note')),
            ],
        ),
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=40, verbose_name='title')),
                ('country', models.CharField(max_length=20, verbose_name='country')),
                ('days', models.IntegerField(default=1, verbose_name='days')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='modifiedtime')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testApp.Group')),
            ],
        ),
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth', models.DateField(null=True, verbose_name='birth')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Dont want to tell', 'Dont want to tell')], max_length=30, null=True, verbose_name='gender')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='photo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='timespan',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.TravelPlan'),
        ),
    ]
