# Generated by Django 2.0 on 2018-04-04 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='start_time')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='duration')),
                ('activity', models.CharField(choices=[('Traffic', 'Traffic'), ('Meal', 'Meal'), ('Sight seeing', 'Sight seeing')], max_length=30, verbose_name='activity')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='note')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.FloatField(default=0.0, verbose_name='expense')),
                ('comment', models.CharField(blank=True, max_length=128, null=True, verbose_name='comment')),
                ('note', models.CharField(blank=True, max_length=100, null=True, verbose_name='note')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manager', models.BooleanField(default=False, verbose_name='is_manager')),
                ('is_creator', models.BooleanField(default=False, verbose_name='is_creator')),
            ],
        ),
        migrations.CreateModel(
            name='TravelGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=40, verbose_name='title')),
                ('is_public', models.BooleanField(default=False, verbose_name='is_public')),
                ('country', models.CharField(max_length=20, verbose_name='country')),
                ('days', models.IntegerField(default=1, verbose_name='days')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='modifiedtime')),
                ('users', models.ManyToManyField(through='testApp.Membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='WebUser',
            new_name='Profile',
        ),
        migrations.RemoveField(
            model_name='group',
            name='users',
        ),
        migrations.RemoveField(
            model_name='timespan',
            name='travel',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='group',
        ),
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='place',
            name='country',
            field=models.CharField(default='', max_length=100, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='place',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='is_public'),
        ),
        migrations.AlterField(
            model_name='place',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='location'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='TimeSpan',
        ),
        migrations.DeleteModel(
            name='TravelPlan',
        ),
        migrations.AddField(
            model_name='membership',
            name='travel_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.TravelGroup'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testApp.Membership'),
        ),
        migrations.AddField(
            model_name='expense',
            name='payees',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='place',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='place', to='testApp.Place'),
        ),
        migrations.AddField(
            model_name='activity',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.TravelGroup'),
        ),
        migrations.AddField(
            model_name='place',
            name='travels',
            field=models.ManyToManyField(blank=True, to='testApp.TravelGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'travel_group')},
        ),
    ]
