# Generated by Django 2.0 on 2017-12-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0003_auto_20171222_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timespan',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='note'),
        ),
    ]
