# Generated by Django 2.0 on 2018-02-12 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0004_auto_20171222_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='start_time')),
                ('duration', models.DurationField(null=True, verbose_name='duration')),
                ('activity', models.CharField(choices=[('Traffic', 'Traffic'), ('Meal', 'Meal'), ('Sight seeing', 'Sight seeing')], max_length=30, verbose_name='activity')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='note')),
                ('expense', models.FloatField(default=0.0, verbose_name='expense')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.FloatField(default=0.0, verbose_name='expense')),
                ('expense_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_activity', to='testApp.Activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.WebUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='timespan',
            name='travel',
        ),
        migrations.AddField(
            model_name='group',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='is_public'),
        ),
        migrations.AddField(
            model_name='group',
            name='manager_id',
            field=models.IntegerField(default=-1, verbose_name='manager_id'),
        ),
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='place',
            name='country',
            field=models.CharField(default='', max_length=100, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='place',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='testApp.WebUser'),
        ),
        migrations.DeleteModel(
            name='TimeSpan',
        ),
        migrations.AddField(
            model_name='activity',
            name='place',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='place', to='testApp.Place'),
        ),
        migrations.AddField(
            model_name='activity',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.TravelPlan'),
        ),
    ]
