# Generated by Django 2.0 on 2018-02-14 18:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testApp', '0006_auto_20180213_0035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebUser',
            new_name='Profile',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='expense',
        ),
    ]
