# Generated by Django 2.0 on 2018-02-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0007_auto_20180214_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='travels',
            field=models.ManyToManyField(to='testApp.TravelPlan'),
        ),
    ]
