# Generated by Django 2.0 on 2018-02-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0008_place_travels'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='is_public'),
        ),
    ]
