# Generated by Django 2.0 on 2018-02-28 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testApp', '0009_place_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=40, verbose_name='title')),
                ('manager_id', models.IntegerField(default=-1, verbose_name='manager_id')),
                ('is_public', models.BooleanField(default=False, verbose_name='is_public')),
                ('country', models.CharField(max_length=20, verbose_name='country')),
                ('days', models.IntegerField(default=1, verbose_name='days')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='modifiedtime')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.TravelGroup'),
        ),
        migrations.AlterField(
            model_name='place',
            name='travels',
            field=models.ManyToManyField(to='testApp.TravelGroup'),
        ),
    ]
