# Generated by Django 2.0 on 2018-02-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0010_auto_20180228_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='location',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='place',
            name='travels',
            field=models.ManyToManyField(blank=True, null=True, to='testApp.TravelGroup'),
        ),
    ]
