# Generated by Django 2.0 on 2018-02-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0011_auto_20180228_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='travels',
            field=models.ManyToManyField(blank=True, to='testApp.TravelGroup'),
        ),
    ]
