# Generated by Django 2.0 on 2018-02-28 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0013_auto_20180228_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='users',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='TravelPlan',
        ),
    ]
