# Generated by Django 2.0 on 2018-03-07 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testApp', '0014_auto_20180228_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='expense_activity',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
        migrations.AddField(
            model_name='expense',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='note'),
        ),
        migrations.AddField(
            model_name='expense',
            name='payee',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='payer_id',
            field=models.IntegerField(default=-1, verbose_name='payer_id'),
        ),
        migrations.AddField(
            model_name='expense',
            name='travel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testApp.TravelGroup'),
        ),
    ]
